import differentiation_theory_gateaux_fr_echet_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differentiation_theory_gateaux_fr_echet_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differentiation_theory_gateaux_fr_echet_theorem_canonical_lane_mathlib
end HautevilleHouse
